### ISSUE TITLE
build 失败

### ISSUE THREAD

**Issue by luckypoem** [coderPerseus/blog#30]
hi.

~/blog-by-coderPerseus (main)$ pnpm build

> lucky-snail-blog@0.1.0 build C:\Users\12799\blog-by-coderPerseus
> next build

  ▲ Next.js 14.2.4

   Creating an optimized production build ...
Warning: Contentlayer might not work as expected on Windows
Warning: Found 1 problems in 43 documents.

 └── Invalid markdown in 1 documents. (Skipping documents)

     • "data/blog/post-26.mdx" failed with YAMLParseError: Unexpected scalar at node end at line 6, column 9:

     tags: []
             ^

Generated 42 documents in .contentlayer
(node:3056) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
<w> [webpack.cache.PackFileCacheStrategy/webpack.FileSystemInfo] Parsing of C:\Users\12799\blog-by-coderPerseus\node_modules\.pnpm\@contentlayer+core@0.3.4_esbuild@0.23.1\node_modules\@contentlayer\core\dist\generation\generate-dotpkg.js for build dependencies failed at 'import(filePathJoin(generatedPkgPath, 'generated', 'index.mjs'))'.
<w> Build dependencies behind this expression are ignored and might cause incorrect cache invalidation.
<w> [webpack.cache.PackFileCacheStrategy/webpack.FileSystemInfo] Parsing of C:\Users\12799\blog-by-coderPerseus\node_modules\.pnpm\@contentlayer+core@0.3.4_esbuild@0.23.1\node_modules\@contentlayer\core\dist\generation\generate-dotpkg.js for build dependencies failed at 'import(filePathJoin(generatedPkgPath, 'generated', 'index.mjs'))'.
<w> Build dependencies behind this expression are ignored and might cause incorrect cache invalidation.
<w> [webpack.cache.PackFileCacheStrategy/webpack.FileSystemInfo] Parsing of C:\Users\12799\blog-by-coderPerseus\node_modules\.pnpm\@contentlayer+core@0.3.4_esbuild@0.23.1\node_modules\@contentlayer\core\dist\generation\generate-dotpkg.js for build dependencies failed at 'import(filePathJoin(generatedPkgPath, 'generated', 'index.mjs'))'.
<w> Build dependencies behind this expression are ignored and might cause incorrect cache invalidation.
 ⚠ Compiled with warnings

./node_modules/.pnpm/framer-motion@11.3.31_react-dom@18.3.1_react@18.3.1/node_modules/framer-motion/dist/es/render/dom/utils/filter-props.mjs
Module not found: Can't resolve '@emotion/is-prop-valid' in 'C:\Users\12799\blog-by-coderPerseus\node_modules\.pnpm\framer-motion@11.3.31_react-dom@18.3.1_react@18.3.1\node_modules\framer-motion\dist\es\render\dom\utils'

Import trace for requested module:
./node_modules/.pnpm/framer-motion@11.3.31_react-dom@18.3.1_react@18.3.1/node_modules/framer-motion/dist/es/render/dom/utils/filter-props.mjs
./node_modules/.pnpm/framer-motion@11.3.31_react-dom@18.3.1_react@18.3.1/node_modules/framer-motion/dist/es/index.mjs
./src/app/not-found.tsx

   Linting and checking validity of types  .(node:19868) [ESLINT_PERSONAL_CONFIG_SUPPRESS] DeprecationWarning: '~/.eslintrc.*' config files have been deprecated. Please remove it or add 'root:true' to the config files in your projects in order to avoid loading '~/.eslintrc.*' accidentally. (found in "..\package.json")
(Use `node --trace-deprecation ...` to show where the warning was created)
 ✓ Linting and checking validity of types
   Collecting page data  ..❌ Invalid environment variables: {
  NEXT_PUBLIC_SITE_URL: [ 'Required' ],
  NEXT_PUBLIC_SITE_EMAIL_FROM: [ 'Required' ]
}
Error: Invalid environment variables
    at 8232 (C:\Users\12799\blog-by-coderPerseus\.next\server\chunks\206.js:16:1562)
    at t (C:\Users\12799\blog-by-coderPerseus\.next\server\webpack-runtime.js:1:128)
    at 9636 (C:\Users\12799\blog-by-coderPerseus\.next\server\app\_not-found\page.js:1:1051)
    at t (C:\Users\12799\blog-by-coderPerseus\.next\server\webpack-runtime.js:1:128)
    at r (C:\Users\12799\blog-by-coderPerseus\.next\server\app\_not-found\page.js:1:3914)
    at C:\Users\12799\blog-by-coderPerseus\.next\server\app\_not-found\page.js:1:3948
    at t.X (C:\Users\12799\blog-by-coderPerseus\.next\server\webpack-runtime.js:1:1206)
    at C:\Users\12799\blog-by-coderPerseus\.next\server\app\_not-found\page.js:1:3927
    at Object.<anonymous> (C:\Users\12799\blog-by-coderPerseus\.next\server\app\_not-found\page.js:1:3975)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)

> Build error occurred
Error: Failed to collect page data for /_not-found
    at C:\Users\12799\blog-by-coderPerseus\node_modules\.pnpm\next@14.2.4_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1\node_modules\next\dist\build\utils.js:1268:15
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5) {
  type: 'Error'
}
   Collecting page data  . ELIFECYCLE  Command failed with exit code 1.

12799@DESKTOP-B6LK9IO MINGW64 ~/blog-by-coderPerseus (main)
$

12799@DESKTOP-B6LK9IO MINGW64 ~/blog-by-coderPerseus (main)
$ ls
LICENSE                 lint-staged.config.ts  posts/
README-zh_CN.md         next-env.d.ts          public/
README.md               next.config.mjs        scripts/
components.json         node_modules/          src/
contentlayer.config.ts  package.json           tailwind.config.ts
data/                   pnpm-lock.yaml         tsconfig.json
env.mjs                 postcss.config.mjs

12799@DESKTOP-B6LK9IO MINGW64 ~/blog-by-coderPerseus (main)
$ find . -name index.html
./node_modules/.pnpm/@tailwindcss+forms@0.5.8_tailwindcss@3.4.10/node_modules/@tailwindcss/forms/index.html

12799@DESKTOP-B6LK9IO MINGW64 ~/blog-by-coderPerseus (main)
$

如何解决？谢谢

**Comment by coderPerseus** [comment]
让我帮你分析这个构建错误并提供解决方案。从错误日志中，我看到有几个主要问题：

1. 环境变量缺失
主要错误是缺少必需的环境变量：
```
❌ Invalid environment variables: {
  NEXT_PUBLIC_SITE_URL: [ 'Required' ],
  NEXT_PUBLIC_SITE_EMAIL_FROM: [ 'Required' ]
}
```

2. MDX文档解析错误
```
Warning: Found 1 problems in 43 documents.
└── Invalid markdown in 1 document. (Skipping documents)
     • "data/blog/post-26.mdx" failed with YAMLParseError
```

3. 依赖问题
```
Module not found: Can't resolve '@emotion/is-prop-valid'
```

解决方案：

1. 创建环境变量文件
在项目根目录创建 `.env.local` 文件（如果没有的话），添加必需的环境变量：
```env
NEXT_PUBLIC_SITE_URL=http://localhost:3000
NEXT_PUBLIC_SITE_EMAIL_FROM=your-email@example.com
```

2. 修复 MDX 文档
检查 `data/blog/post-26.mdx` 文件的 frontmatter 部分，特别是第6行的 YAML 语法错误。确保 YAML 格式正确：
```yaml
---
title: "Your Title"
date: "2024-01-01"
tags: [] # 这里可能需要修复
---
```

3. 安装缺失的依赖
运行以下命令安装缺失的依赖：
```bash
pnpm add @emotion/is-prop-valid
```

4. 清理缓存并重新构建
```bash
# 清理 Next.js 缓存
rm -rf .next
# 清理依赖缓存
pnpm store prune
# 重新安装依赖
pnpm install
# 重新构建
pnpm build
```

建议按照以上步骤逐一解决问题。如果还有问题，请检查：

1. 确保所有环境变量都已正确设置
2. 检查 MDX 文件的格式
3. 确保所有依赖都已正确安装
4. 如果使用了 contentlayer，确保配置文件 `contentlayer.config.ts` 设置正确

如果按照以上步骤操作后还有具体问题，请告诉我具体的错误信息，我会继续帮你解决。

**Comment by luckypoem** [comment]
谢谢你。问题解决了。
你是我遇到的最细心解决用户问题的人。要给你大大的赞。
